# Generated by Django 6.1 on 2026-08-13 19:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_api_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='setentry',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='workout_type',
            field=models.CharField(choices=[('lifting', 'Lifting'), ('running', 'Running'), ('biking', 'Biking'), ('swimming', 'Swimming')], default='lifting', max_length=20),
        ),
    ]
