# Generated by Django 6.1 on 2026-08-14 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sessionroutepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionroutepoint',
            name='speed_mps',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
