# Generated by Django 6.1 on 2026-08-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sessionroutepoint_speed_mps'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionroutepoint',
            name='altitude_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
