# Generated by Django 6.1 on 2026-08-15 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sessionroutepoint_altitude_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='cardio_distance_km',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='cardio_machine',
            field=models.CharField(blank=True, choices=[('treadmill', 'Treadmill'), ('stationary_bike', 'Stationary Bike'), ('stair_master', 'Stair Master'), ('elliptical', 'Elliptical'), ('rowing_machine', 'Rowing Machine'), ('assault_bike', 'Assault Bike'), ('ski_erg', 'Ski Erg'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='cardio_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='cardio_machine',
            field=models.CharField(blank=True, choices=[('treadmill', 'Treadmill'), ('stationary_bike', 'Stationary Bike'), ('stair_master', 'Stair Master'), ('elliptical', 'Elliptical'), ('rowing_machine', 'Rowing Machine'), ('assault_bike', 'Assault Bike'), ('ski_erg', 'Ski Erg'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='cardio_target_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
