# Generated by Django 6.1 on 2026-08-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_workoutsession_cardio_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='cardio_machine',
            field=models.CharField(blank=True, choices=[('treadmill', 'Treadmill'), ('stationary_bike', 'Stationary Bike'), ('stair_master', 'Stair Master'), ('elliptical', 'Elliptical'), ('rowing_machine', 'Rowing Machine'), ('assault_bike', 'Assault Bike'), ('ski_erg', 'Ski Erg'), ('other', 'Other')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='cardio_machine',
            field=models.CharField(blank=True, choices=[('treadmill', 'Treadmill'), ('stationary_bike', 'Stationary Bike'), ('stair_master', 'Stair Master'), ('elliptical', 'Elliptical'), ('rowing_machine', 'Rowing Machine'), ('assault_bike', 'Assault Bike'), ('ski_erg', 'Ski Erg'), ('other', 'Other')], default=None, max_length=20, null=True),
        ),
    ]
