# Generated by Django 6.1 on 2026-08-15 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_workoutsession_cardio_machine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_until', models.DateField(blank=True, db_index=True, null=True)),
                ('materialized_through', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_recurrences', to='core.repbaseuser')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='core.workouttemplate')),
            ],
            options={
                'ordering': ('weekday', 'id'),
            },
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='source_recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_schedules', to='core.workoutrecurrence'),
        ),
        migrations.AddConstraint(
            model_name='workoutrecurrence',
            constraint=models.UniqueConstraint(condition=models.Q(('effective_until__isnull', True)), fields=('owner', 'workout', 'weekday'), name='unique_open_recurrence_per_weekday'),
        ),
    ]
