# Generated by Django 6.1 on 2026-08-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workoutrecurrence_workoutschedule_source_recurrence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task', 'Task'), ('event', 'Event')], default='task', max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('habit', 'Habit'), ('workout', 'Workout'), ('errand', 'Errand'), ('study', 'Study'), ('sleep', 'Sleep'), ('health', 'Health'), ('work', 'Work'), ('home', 'Home'), ('other', 'Other')], default='other', max_length=20)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_entries', to='core.repbaseuser')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner_entries', to='core.workouttemplate')),
            ],
            options={
                'ordering': ('scheduled_date', 'scheduled_time', 'id'),
                'indexes': [models.Index(fields=['owner', 'scheduled_date'], name='core_planne_owner_i_0363dc_idx')],
            },
        ),
    ]
