# Generated by Django 6.1 on 2026-08-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_plannerentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannerentry',
            name='category',
            field=models.CharField(choices=[('habit', 'Habit'), ('workout', 'Workout'), ('errand', 'Errand'), ('study', 'Study'), ('sleep', 'Sleep'), ('health', 'Health'), ('work', 'Work'), ('home', 'Home'), ('birthday', 'Birthday'), ('holiday', 'Holiday'), ('appointment', 'Appointment'), ('meeting', 'Meeting'), ('travel', 'Travel'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
