# Generated by Django 6.1 on 2026-08-16 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_plannerentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repbaseuser',
            name='training_style',
            field=models.CharField(blank=True, choices=[('powerlifting', 'Powerlifting'), ('bodybuilding', 'Bodybuilding'), ('crossfit', 'CrossFit'), ('weightlifting', 'Olympic weightlifting'), ('rock_climbing', 'Rock climbing'), ('triathlon', 'Triathlon'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('calisthenics', 'Calisthenics'), ('general_fitness', 'General fitness'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=150)),
                ('normalized_city', models.CharField(db_index=True, editable=False, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gyms', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('name', 'city'),
            },
        ),
        # The old field was free text. Converting it in place carries the
        # existing empty strings into the foreign key column, where an empty
        # string is not a valid id and the migration fails SQLite's foreign key
        # check. No profile had a gym set, so the column is dropped and
        # recreated rather than converted.
        migrations.RemoveField(
            model_name='repbaseuser',
            name='gym',
        ),
        migrations.AddField(
            model_name='repbaseuser',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.gym'),
        ),
        migrations.AddConstraint(
            model_name='gym',
            constraint=models.UniqueConstraint(fields=('normalized_name', 'normalized_city'), name='unique_gym_per_city'),
        ),
    ]
