# Generated by Django 6.1 on 2026-08-16, then reordered by hand.
#
# The generated version removed the old columns before adding the new ones,
# which would have thrown away every value on the way past. The additions run
# first, a data step carries the old values across, and only then are the old
# columns dropped.

import core.models
import django.db.models.deletion
from django.db import migrations, models


def carry_values_forward(apps, schema_editor):
    """One visibility flag becomes three, one training style becomes a row.

    A profile that was sharing its measurements keeps sharing all three, since
    that is exactly what the single flag meant. A profile that was not stays
    private by default.
    """
    RepbaseUser = apps.get_model("core", "RepbaseUser")
    UserDiscipline = apps.get_model("core", "UserDiscipline")

    for profile in RepbaseUser.objects.all():
        if profile.is_body_metrics_public:
            profile.shows_height = True
            profile.shows_weight = True
            profile.shows_target_weight = True
            profile.save(
                update_fields=["shows_height", "shows_weight", "shows_target_weight"]
            )
        if profile.training_style:
            UserDiscipline.objects.get_or_create(
                profile=profile,
                discipline=profile.training_style,
            )


def put_values_back(apps, schema_editor):
    """Reverses as far as it can.

    The three flags collapse back to one if any of them is on, and the first
    discipline becomes the training style again. Going backwards genuinely
    loses information, which is what the forward direction bought.
    """
    RepbaseUser = apps.get_model("core", "RepbaseUser")

    for profile in RepbaseUser.objects.all():
        profile.is_body_metrics_public = any(
            [profile.shows_height, profile.shows_weight, profile.shows_target_weight]
        )
        first = profile.disciplines.order_by("discipline").first()
        profile.training_style = first.discipline if first else ""
        profile.save(update_fields=["is_body_metrics_public", "training_style"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_repbaseuser_training_style_gym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repbaseuser',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='repbaseuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.profile_photo_path),
        ),
        migrations.AddField(
            model_name='repbaseuser',
            name='shows_height',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repbaseuser',
            name='shows_target_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='repbaseuser',
            name='shows_weight',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('powerlifting', 'Powerlifting'), ('bodybuilding', 'Bodybuilding'), ('crossfit', 'CrossFit'), ('weightlifting', 'Olympic weightlifting'), ('rock_climbing', 'Rock climbing'), ('triathlon', 'Triathlon'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('calisthenics', 'Calisthenics'), ('general_fitness', 'General fitness'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('discipline',),
                'constraints': [models.UniqueConstraint(fields=('profile', 'discipline'), name='unique_discipline_per_profile')],
            },
        ),
        migrations.RunPython(carry_values_forward, put_values_back),
        migrations.RemoveField(
            model_name='repbaseuser',
            name='is_body_metrics_public',
        ),
        migrations.RemoveField(
            model_name='repbaseuser',
            name='profile_photo_url',
        ),
        migrations.RemoveField(
            model_name='repbaseuser',
            name='training_style',
        ),
    ]
