# Generated by Django 6.1 on 2026-08-17 01:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_repbaseuser_is_body_metrics_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_meals', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('date', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('servings', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('calories', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_grams', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrate_grams', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_grams', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.foodmeal')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.DecimalField(decimal_places=2, default=Decimal('2000'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_grams', models.DecimalField(decimal_places=2, default=Decimal('150'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrate_grams', models.DecimalField(decimal_places=2, default=Decimal('200'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_grams', models.DecimalField(decimal_places=2, default=Decimal('70'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to='core.repbaseuser')),
            ],
        ),
        migrations.CreateModel(
            name='SavedFoodMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_food_meals', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SavedFoodIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('servings', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('calories', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_grams', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrate_grams', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_grams', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('saved_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='core.savedfoodmeal')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='foodmeal',
            index=models.Index(fields=['owner', 'date'], name='core_foodme_owner_i_253461_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedfoodmeal',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_saved_meal_name_per_owner'),
        ),
    ]
