# Generated by Django 6.1 on 2026-08-18 03:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_foodmeal_foodentry_nutritiongoal_savedfoodmeal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('workout', 'Workout'), ('meal', 'Meal'), ('planner', 'Planner')], max_length=20)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.repbaseuser')),
                ('source_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.foodmeal')),
                ('source_planner_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.plannerentry')),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.workoutsession')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PostMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostMealEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('servings', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('calories', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_grams', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbohydrate_grams', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat_grams', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('post_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.postmeal')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PostPlannerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task', 'Task'), ('event', 'Event')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('habit', 'Habit'), ('workout', 'Workout'), ('errand', 'Errand'), ('study', 'Study'), ('sleep', 'Sleep'), ('health', 'Health'), ('work', 'Work'), ('home', 'Home'), ('birthday', 'Birthday'), ('holiday', 'Holiday'), ('appointment', 'Appointment'), ('meeting', 'Meeting'), ('travel', 'Travel'), ('social', 'Social'), ('other', 'Other')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('workout_type', models.CharField(blank=True, choices=[('lifting', 'Lifting'), ('running', 'Running'), ('biking', 'Biking'), ('swimming', 'Swimming')], default=None, max_length=20, null=True)),
                ('performed_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('cardio_machine', models.CharField(blank=True, choices=[('treadmill', 'Treadmill'), ('stationary_bike', 'Stationary Bike'), ('stair_master', 'Stair Master'), ('elliptical', 'Elliptical'), ('rowing_machine', 'Rowing Machine'), ('assault_bike', 'Assault Bike'), ('ski_erg', 'Ski Erg'), ('other', 'Other')], default=None, max_length=20, null=True)),
                ('cardio_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('cardio_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('route_distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pace_seconds_per_km', models.PositiveIntegerField(blank=True, null=True)),
                ('elevation_gain_m', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='core.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostWorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=1)),
                ('set_count', models.PositiveIntegerField(default=0)),
                ('top_set_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('top_set_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('total_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('volume_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('post_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.postworkout')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='core.repbaseuser')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['blocked', 'blocker'], name='core_block_blocked_aae3fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_block_per_pair'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='block_is_not_self')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='core.repbaseuser')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['following', '-created_at'], name='core_follow_followi_d81e8c_idx'), models.Index(fields=['follower', '-created_at'], name='core_follow_followe_d0561e_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'following'), name='unique_follow_per_pair'), models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='follow_is_not_self')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at', '-id'], name='core_post_author__59bbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at', '-id'], name='core_post_created_1e8110_idx'),
        ),
    ]
