# Generated by Django 6.1 on 2026-08-18 19:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_post_postmeal_postmealentry_postplannerentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.post_photo_path),
        ),
    ]
