# Generated by Django 6.1 on 2026-08-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_post_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plannerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'task'), ('workout__isnull', False)), fields=('owner', 'workout', 'scheduled_date'), name='unique_workout_task_per_day'),
        ),
    ]
