# Generated by Django 6.1 on 2026-08-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_plannerentry_unique_workout_task_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='planner_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
