# Generated by Django 6.1 on 2026-08-19 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_workoutschedule_planner_synced_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStepCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('steps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_step_counts', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('-day',),
                'constraints': [models.UniqueConstraint(fields=('owner', 'day'), name='unique_step_count_per_day')],
            },
        ),
    ]
