# Generated by Django 6.1 on 2026-08-19 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_dailystepcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='health_distance_km',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='health_external_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('health_external_id__isnull', False)), fields=('repbase_user', 'health_external_id'), name='unique_health_workout_per_user'),
        ),
    ]
