# Generated by Django 6.1 on 2026-08-19 22:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_workoutsession_health_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='recorded_distance_km',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('shoe', 'Shoe'), ('bike', 'Bike')], max_length=8)),
                ('name', models.CharField(max_length=80)),
                ('brand', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('initial_distance_km', models.DecimalField(decimal_places=3, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('retire_at_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_default', models.BooleanField(default=False)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('kind', 'name'),
            },
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='gear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.gear'),
        ),
        migrations.AddConstraint(
            model_name='gear',
            constraint=models.UniqueConstraint(fields=('owner', 'kind', 'name'), name='unique_gear_name_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='gear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner', 'kind'), name='one_default_gear_per_kind'),
        ),
    ]
