# Generated by Django 6.1 on 2026-08-21 00:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_workoutsession_recorded_distance_km_gear_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('length', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('anchor_date', models.DateField()),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_until', models.DateField(blank=True, db_index=True, null=True)),
                ('materialized_through', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_cycles', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('-effective_from', '-id'),
            },
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='source_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_schedules', to='core.workoutcycle'),
        ),
        migrations.CreateModel(
            name='WorkoutCycleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.workoutcycle')),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_slots', to='core.workouttemplate')),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('cycle', 'position'), name='unique_slot_position_per_cycle')],
            },
        ),
    ]
