# Generated by Django 6.1 on 2026-08-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_post_repost_of_alter_post_kind_postcomment_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shows_weights',
            field=models.BooleanField(default=True),
        ),
    ]
