# Generated by Django 6.1 on 2026-08-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_post_shows_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='repbaseuser',
            name='daily_step_goal',
            field=models.PositiveIntegerField(default=8000),
        ),
    ]
