# Generated by Django 6.1 on 2026-08-25 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_repbaseuser_daily_step_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_highlights', to='core.exercise')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('owner', 'exercise'), name='unique_highlight_per_owner')],
            },
        ),
        migrations.CreateModel(
            name='ProfilePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('why_i_train', 'Why I train'), ('current_goal', 'What I am working towards'), ('favourite_lift', 'Favourite lift'), ('hardest_part', 'The hardest part for me'), ('best_advice', 'Best advice I have been given'), ('proudest', 'Proudest moment in the gym'), ('rest_day', 'A rest day looks like'), ('pre_workout', 'What I eat before training'), ('post_workout', 'What I eat after'), ('training_to', 'What I train to'), ('one_more_rep', 'What gets me one more rep'), ('training_partner', 'Looking for a training partner who')], max_length=24)),
                ('answer', models.CharField(max_length=140)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('owner', 'question'), name='unique_prompt_per_owner')],
            },
        ),
    ]
