# Generated by Django 6.1 on 2026-08-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_profilehighlight_profileprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='repbaseuser',
            name='time_zone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
