# Generated by Django 6.1 on 2026-08-25 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_repbaseuser_time_zone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profilehighlight',
            name='unique_highlight_per_owner',
        ),
        migrations.AddField(
            model_name='profilehighlight',
            name='lift',
            field=models.CharField(choices=[('bench', 'Bench Press'), ('squat', 'Squat'), ('deadlift', 'Deadlift')], default='bench', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilehighlight',
            name='manual_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilehighlight',
            name='manual_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='profilehighlight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='profilehighlight',
            constraint=models.UniqueConstraint(fields=('owner', 'lift'), name='unique_highlight_lift_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='profilehighlight',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('manual_reps__isnull', True), ('manual_weight_kg__isnull', True)), models.Q(('manual_reps__isnull', False), ('manual_weight_kg__isnull', False)), _connector='OR'), name='manual_highlight_is_whole'),
        ),
        migrations.RemoveField(
            model_name='profilehighlight',
            name='exercise',
        ),
    ]
