# Generated by Django 6.1 on 2026-08-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_profilehighlight_unique_highlight_per_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileprompt',
            name='question',
            field=models.CharField(choices=[('why_i_train', 'Why I train'), ('current_goal', 'What I am working towards'), ('proudest', 'Proudest moment in the gym'), ('hardest_part', 'The hardest part for me'), ('started_because', 'I started training because'), ('training_changed', 'Training changed this about me'), ('favourite_lift', 'Favourite lift'), ('skipped_lift', 'The lift I skip if I can'), ('one_more_rep', 'What gets me one more rep'), ('best_advice', 'Best advice I have been given'), ('training_to', 'What I train to'), ('gym_pet_peeve', 'My gym pet peeve'), ('warm_up', 'My warm-up is'), ('pre_workout', 'What I eat before training'), ('post_workout', 'What I eat after'), ('worth_it', 'Worth every calorie'), ('on_repeat', 'The meal I make on repeat'), ('rest_day', 'A rest day looks like'), ('outside_gym', 'Outside the gym you will find me'), ('recovery', 'How I actually recover'), ('sunday', 'My Sunday in three words'), ('training_partner', 'Looking for a training partner who'), ('spot_me', 'Ask me to spot you if'), ('partner_never', 'A training partner should never')], max_length=24),
        ),
    ]
