# Generated by Django 6.1 on 2026-08-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_profileprompt_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannerentry',
            options={'ordering': ('scheduled_date', models.Case(models.When(priority='high', then=models.Value(0)), models.When(priority='normal', then=models.Value(1)), default=models.Value(2), output_field=models.IntegerField()), 'scheduled_time', 'id')},
        ),
        migrations.AddField(
            model_name='plannerentry',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10),
        ),
    ]
