# Generated by Django 6.1 on 2026-08-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_plannerentry_options_plannerentry_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerentry',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='plannerentry',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__isnull', True), ('scheduled_time__isnull', False), _connector='OR'), name='duration_needs_a_start_time'),
        ),
        migrations.AddConstraint(
            model_name='plannerentry',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__isnull', True), models.Q(('duration_minutes__gte', 5), ('duration_minutes__lte', 1440)), _connector='OR'), name='duration_within_bounds'),
        ),
    ]
