# Generated by Django 6.1 on 2026-08-26 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_plannerentry_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or misleading'), ('harassment', 'Harassment or bullying'), ('hate', 'Hate speech'), ('violence', 'Violence or threats'), ('nudity', 'Nudity or sexual content'), ('harm', 'Promotes self-harm or disordered eating'), ('advice', 'Dangerous or false advice'), ('other', 'Something else')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.post')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['post', 'created_at'], name='core_postre_post_id_ce8f4c_idx')],
                'constraints': [models.UniqueConstraint(fields=('post', 'reporter'), name='one_report_per_person_per_post')],
            },
        ),
    ]
