# Generated by Django 6.1 on 2026-08-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_postreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('snapchat', 'Snapchat'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('x', 'X'), ('website', 'Website')], max_length=12)),
                ('url', models.URLField(max_length=300)),
                ('handle', models.CharField(blank=True, max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('position', 'id'),
                'constraints': [models.UniqueConstraint(fields=('owner', 'platform'), name='unique_social_link_per_owner')],
            },
        ),
    ]
