# Generated by Django 6.1 on 2026-08-26 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_profilesociallink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postreport',
            name='resolution',
            field=models.CharField(blank=True, choices=[('no_action', 'Looked, no action needed'), ('hidden', 'Post hidden'), ('deleted', 'Post deleted')], max_length=20),
        ),
        migrations.AddField(
            model_name='postreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_post_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
