# Generated by Django 6.1 on 2026-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, unique=True)),
                ('payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-fetched_at',),
            },
        ),
    ]
