# Generated by Django 6.1 on 2026-08-27 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_foodsearchcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intents', models.JSONField(blank=True, default=list)),
                ('training_types', models.JSONField(blank=True, default=list)),
                ('weekly_target', models.PositiveSmallIntegerField(default=3)),
                ('experience', models.CharField(blank=True, max_length=40)),
                ('emphasis', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repbase_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personalization', to='core.repbaseuser')),
            ],
        ),
    ]
