# Generated by Django 6.1 on 2026-08-27 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_personalization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalization',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='personalization',
            name='intents',
        ),
    ]
