# Generated by Django 6.1 on 2026-08-30 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_personalization_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfoodmeal',
            name='source_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_copies', to='core.post'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='source_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_copies', to='core.post'),
        ),
    ]
