# Generated by Django 6.1 on 2026-09-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_savedfoodmeal_source_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repbaseuser',
            name='is_profile_public',
            field=models.BooleanField(default=True),
        ),
    ]
