# Generated by Django 6.1 on 2026-09-01 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_repbaseuser_is_profile_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_sent', to='core.repbaseuser')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_requests_received', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('requester', 'target'), name='unique_follow_request'), models.CheckConstraint(condition=models.Q(('requester', models.F('target')), _negated=True), name='no_self_follow_request')],
            },
        ),
    ]
