# Generated by Django 6.1 on 2026-09-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('follow', 'Started following you'), ('follow_request', 'Asked to follow you'), ('follow_approved', 'Accepted your follow request'), ('like', 'Liked your post'), ('repost', 'Reposted your post'), ('comment', 'Commented on your post')], max_length=20),
        ),
    ]
