# Generated by Django 6.1 on 2026-09-03 23:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_notification_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feed_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.post_feed_photo_path),
        ),
    ]
