# Generated by Django 6.1 on 2026-09-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_post_feed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmeal',
            name='cooking_instructions',
            field=models.TextField(blank=True),
        ),
    ]
