# Generated by Django 6.1 on 2026-09-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_postmeal_cooking_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfoodmeal',
            name='cooking_instructions',
            field=models.TextField(blank=True),
        ),
    ]
