# Generated by Django 6.1 on 2026-09-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_pendingmediadeletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('path', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('response', models.JSONField()),
                ('status_code', models.PositiveSmallIntegerField(default=201)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repbaseuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'path', 'key'), name='unique_save_receipt')],
            },
        ),
    ]
