# Generated by Django 6.1 on 2026-09-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_save_receipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsearchcache',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='savereceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
