# Generated by Django 6.1 on 2026-09-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_case_insensitive_account_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='route_summary',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
