# Generated by Django 6.1 on 2026-09-15 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_email_lookup_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or misleading'), ('harassment', 'Harassment or bullying'), ('hate', 'Hate speech'), ('violence', 'Violence or threats'), ('nudity', 'Nudity or sexual content'), ('harm', 'Promotes self-harm or disordered eating'), ('advice', 'Dangerous or false advice'), ('other', 'Something else')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('no_action', 'Looked, no action needed'), ('hidden', 'Post hidden'), ('deleted', 'Post deleted')], max_length=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.postcomment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to='core.repbaseuser')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['reviewed_at', 'created_at'], name='comment_report_review_idx')],
                'constraints': [models.UniqueConstraint(fields=('comment', 'reporter'), name='one_comment_report_per_person')],
            },
        ),
    ]
