# Generated by Django 6.1 on 2026-09-16 00:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_comment_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feed_image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to=core.models.post_feed_photo_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to=core.models.post_photo_path),
        ),
    ]
