# Generated by Django 6.1 on 2026-09-19 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_media_takedown_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannerentry',
            name='is_subtask',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='plannerentry',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.plannerentry'),
        ),
        migrations.AddConstraint(
            model_name='plannerentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_subtask', False), ('parent__isnull', True)), models.Q(('is_subtask', True), ('parent__isnull', False)), _connector='OR'), name='is_subtask_matches_parent'),
        ),
        migrations.AddConstraint(
            model_name='plannerentry',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), ('kind', 'task'), _connector='OR'), name='only_tasks_have_parents'),
        ),
    ]
