# Generated by Django 6.1 on 2026-09-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_subtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveSmallIntegerField(default=1)),
                ('starts_on', models.DateField(db_index=True)),
                ('ends_on', models.DateField(blank=True, db_index=True, null=True)),
                ('materialized_through', models.DateField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('habit', 'Habit'), ('workout', 'Workout'), ('errand', 'Errand'), ('study', 'Study'), ('sleep', 'Sleep'), ('health', 'Health'), ('work', 'Work'), ('home', 'Home'), ('birthday', 'Birthday'), ('holiday', 'Holiday'), ('appointment', 'Appointment'), ('meeting', 'Meeting'), ('travel', 'Travel'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(default='normal', max_length=10)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner_recurrences', to='core.repbaseuser')),
            ],
            options={
                'ordering': ('starts_on', 'id'),
            },
        ),
        migrations.AddField(
            model_name='plannerentry',
            name='recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='core.plannerrecurrence'),
        ),
        migrations.AddConstraint(
            model_name='plannerrecurrence',
            constraint=models.CheckConstraint(condition=models.Q(('interval_days__gte', 1), ('interval_days__lte', 365)), name='planner_repeat_interval_within_bounds'),
        ),
        migrations.AddConstraint(
            model_name='plannerrecurrence',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gt', models.F('starts_on')), _connector='OR'), name='planner_repeat_ends_after_it_starts'),
        ),
    ]
