# Generated by Django 6.1 on 2026-09-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_planner_repeats'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannerRecurrenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('recurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.plannerrecurrence')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
    ]
