# Generated by Django 6.1 on 2026-09-20 07:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('core', '0058_repeat_steps'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=10)),
                ('community_enabled', models.BooleanField(default=False)),
                ('generation', models.UUIDField(default=uuid.uuid4)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.repbaseuser')),
            ],
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_generation', models.UUIDField()),
                ('status', models.CharField(default='queued', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease', models.UUIDField(null=True)),
                ('last_error', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notification')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pushdevice')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pushdevice',
            constraint=models.UniqueConstraint(fields=('token', 'environment'), name='unique_apns_device'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['status', 'next_attempt'], name='push_dispatch_due'),
        ),
        migrations.AddConstraint(
            model_name='pushdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'device'), name='unique_notification_device_push'),
        ),
    ]
