# Generated by Django 6.1 on 2026-09-20 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_pushdevice_pushdelivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_email', models.EmailField(max_length=254)),
                ('verified_at', models.DateTimeField()),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyApiMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('endpoint', models.CharField(max_length=160)),
                ('method', models.CharField(max_length=8)),
                ('requests', models.PositiveBigIntegerField(default=0)),
                ('client_errors', models.PositiveBigIntegerField(default=0)),
                ('server_errors', models.PositiveBigIntegerField(default=0)),
                ('total_ms', models.PositiveBigIntegerField(default=0)),
                ('max_ms', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('day', 'endpoint', 'method'), name='unique_daily_api_metric')],
            },
        ),
        migrations.CreateModel(
            name='DailyActiveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('day', 'user'), name='unique_daily_active_account')],
            },
        ),
    ]
