# Generated by Django 6.1 on 2026-10-10 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('not_interested', 'Not interested')], default='not_interested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('total_dwell_ms', models.PositiveBigIntegerField(default=0)),
                ('max_watch_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('skipped', models.BooleanField(default=False)),
                ('surface', models.CharField(choices=[('for_you', 'For You'), ('following', 'Following'), ('discover', 'Discover'), ('profile', 'Profile'), ('other', 'Other')], default='other', max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['author', '-created_at'], name='core_postco_author__6d6dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['user', '-created_at'], name='core_postli_user_id_2a1e25_idx'),
        ),
        migrations.AddField(
            model_name='postfeedback',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.post'),
        ),
        migrations.AddField(
            model_name='postfeedback',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_feedback', to='core.repbaseuser'),
        ),
        migrations.AddField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.post'),
        ),
        migrations.AddField(
            model_name='postview',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='core.repbaseuser'),
        ),
        migrations.AddIndex(
            model_name='postfeedback',
            index=models.Index(fields=['viewer', '-created_at'], name='core_postfe_viewer__02fbc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='postfeedback',
            constraint=models.UniqueConstraint(fields=('viewer', 'post'), name='one_feedback_per_pair'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['viewer', '-last_seen_at'], name='core_postvi_viewer__2b4b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['surface', 'first_seen_at'], name='core_postvi_surface_867e68_idx'),
        ),
        migrations.AddConstraint(
            model_name='postview',
            constraint=models.UniqueConstraint(fields=('viewer', 'post'), name='one_view_row_per_pair'),
        ),
    ]
