# Generated by Django 6.1 on 2026-09-21 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_account_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaccess',
            name='superowner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='accountaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('superowner', True)), fields=('superowner',), name='one_app_superowner'),
        ),
    ]
