# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_superowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentApiMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.DateTimeField(db_index=True)),
                ('endpoint', models.CharField(max_length=160)),
                ('method', models.CharField(max_length=8)),
                ('requests', models.PositiveBigIntegerField(default=0)),
                ('client_errors', models.PositiveBigIntegerField(default=0)),
                ('server_errors', models.PositiveBigIntegerField(default=0)),
                ('total_ms', models.PositiveBigIntegerField(default=0)),
                ('max_ms', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='recentapimetric',
            constraint=models.UniqueConstraint(fields=('bucket', 'endpoint', 'method'), name='unique_recent_api_metric'),
        ),
    ]
