# Generated by Django 6.1 on 2026-09-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_superowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaccess',
            name='disabled_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountaccess',
            name='session_epoch',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
