# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_recentapimetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=160)),
                ('method', models.CharField(max_length=8)),
                ('kind', models.CharField(choices=[('failing', 'Server errors'), ('slow', 'Slow responses')], max_length=10)),
                ('opened_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('detail', models.CharField(default='', max_length=200)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('resolved_at__isnull', True)), fields=('endpoint', 'method', 'kind'), name='one_open_alert_per_route_and_kind')],
            },
        ),
    ]
