# Generated by Django 6.1 on 2026-09-22 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_account_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountaccess',
            name='label_color',
            field=models.CharField(default='#F65A18', max_length=7),
        ),
        migrations.AddField(
            model_name='accountaccess',
            name='public_badge',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='accountaccess',
            name='public_label',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='CommunitySpotlight',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('announcement', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveIntegerField(default=0)),
                ('featured_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.post')),
            ],
        ),
    ]
