# Generated by Django 6.1 on 2026-10-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_apialert'),
        ('core', '0064_community_tools'),
    ]

    operations = [
    ]
