"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-development-only-change-before-deployment',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() in {'1', 'true', 'yes'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Uploaded profile photos. Served by Django only while DEBUG is on; a real
# deployment puts a web server or object store in front of this.
# Django refuses a request body larger than this before any view sees it, and
# answers with HTML rather than the JSON the app expects. The default of 2.5 MB
# is below a 5 MB photo once base64 has added a third, so the profile photo
# limit would never have been the one doing the refusing.
DATA_UPLOAD_MAX_MEMORY_SIZE = 8 * 1024 * 1024

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Uploaded photos are served by core.media behind a keyed signature, in every
# configuration rather than only under DEBUG. See that module for why the
# expiry is rounded rather than exact -- in short, a URL that changes on every
# read is a URL nothing can cache.
MEDIA_URL_TTL = int(os.getenv('REPBASE_MEDIA_URL_TTL', str(7 * 24 * 60 * 60)))
MEDIA_URL_WINDOW = int(os.getenv('REPBASE_MEDIA_URL_WINDOW', str(24 * 60 * 60)))

# Set this to the internal location a reverse proxy maps onto MEDIA_ROOT --
# `/protected-media/` for a standard nginx `internal;` block -- and the file
# is sent by the proxy while this process only checks the signature and
# returns a header. Left empty, Django sends the bytes itself, which works and
# is what development uses.
MEDIA_ACCEL_REDIRECT_ROOT = os.getenv('REPBASE_MEDIA_ACCEL_REDIRECT_ROOT', '')


# API

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Generous for a signed-in person: the app fans out a dozen or so
        # calls on launch and a few per screen after that, so a ceiling low
        # enough to bite normal use would be worse than none.
        'user': os.environ.get('REPBASE_THROTTLE_USER', '1200/hour'),
        # Anonymous traffic is registration, login and the schema. Nothing
        # legitimate needs many.
        'anon': os.environ.get('REPBASE_THROTTLE_ANON', '60/hour'),
        # Tight on purpose. This is the one endpoint where the attempt is
        # itself the attack, and a person who has forgotten their password
        # does not try twenty times in a minute.
        'login': os.environ.get('REPBASE_THROTTLE_LOGIN', '10/hour'),
        # Registration from one address, which is how throwaway accounts get
        # made in bulk.
        'register': os.environ.get('REPBASE_THROTTLE_REGISTER', '10/day'),
        # Writes that create content other people see.
        'post': os.environ.get('REPBASE_THROTTLE_POST', '60/hour'),
        # Asking for a reset code, and guessing at one. Both are cheap to
        # attempt and expensive to get wrong, and neither is something a
        # person does repeatedly.
        'password_reset': os.environ.get('REPBASE_THROTTLE_RESET', '6/hour'),
        # Per person, so one of them cannot spend the FoodData Central
        # allowance the whole userbase shares. Generous, because the
        # cache absorbs anything anyone has searched for lately.
        'food_search': os.environ.get('REPBASE_THROTTLE_FOOD', '120/hour'),
        # Wider, because a person who mistypes a code needs several
        # tries and the code itself only allows five before it is
        # spent. Five tries at six codes is the honest ceiling.
        'password_reset_confirm': os.environ.get(
            'REPBASE_THROTTLE_RESET_CONFIRM', '30/hour'
        ),
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Repbase API',
    'DESCRIPTION': 'Versioned API for the Repbase iOS application.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/v1',
    # Two choice sets are each reached through fields with different names --
    # a workout's type is on the template, the posted snapshot and the step
    # count; the cardio machine on the template, the snapshot and the session.
    # Left alone, drf-spectacular emitted one component per field name and
    # warned that it had to guess: the same four workout types were
    # WorkoutTypeEnum in one place and ActivityEnum in another, and the same
    # eight machines were MachineEnum and CardioMachineEnum.
    #
    # That matters beyond tidiness, because these names become the generated
    # Swift types. Duplicates mean the client holds two unrelated types for
    # one set and has to convert between them, and which name a field gets
    # can change when somebody adds an unrelated field elsewhere.
    #
    # The names kept are the ones that say what the value is. "Machine" alone
    # does not, and "Activity" reads like something other than a workout type.
    'ENUM_NAME_OVERRIDES': {
        'WorkoutTypeEnum': 'core.models.WorkoutTypeChoices.choices',
        'CardioMachineEnum': 'core.models.CardioMachine.choices',
    },
}

SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG and os.getenv(
    'DJANGO_SECURE_SSL_REDIRECT',
    'true',
).lower() in {'1', 'true', 'yes'}
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# This product sends one email: a password reset code, to somebody who is
# already locked out of their account. There is no retry queue and no second
# channel, so email that cannot deliver is not a degraded feature -- it is an
# account nobody can get back into. core.checks refuses to let a production
# deploy discover that from its first locked-out user.

if DEBUG:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        },
    }
else:
    # Implicit TLS on port 465, or STARTTLS on 587, depending on the
    # provider. Django refuses both at once, so asking for SSL settles it
    # rather than raising on the combination that reads as more secure.
    _smtp_ssl = os.getenv('SMTP_USE_SSL', 'false').lower() in {'1', 'true', 'yes'}
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': os.getenv('SMTP_HOST', 'localhost'),
                'port': int(os.getenv('SMTP_PORT', '587')),
                'username': os.getenv('SMTP_USERNAME', ''),
                'password': os.getenv('SMTP_PASSWORD', ''),
                'use_ssl': _smtp_ssl,
                'use_tls': False if _smtp_ssl else os.getenv(
                    'SMTP_USE_TLS', 'true'
                ).lower() in {'1', 'true', 'yes'},
                # Django's default is no timeout at all. A provider that
                # accepts the connection and then stops talking would hold
                # the worker serving that request until the socket gave up
                # on its own, and on a small deployment one worker is a
                # noticeable share of the server.
                'timeout': int(os.getenv('SMTP_TIMEOUT', '10')),
            },
        },
    }

# FoodData Central. Free, and rate limited per IP -- which is one IP for
# everybody once the lookup is proxied through here, so FoodSearchCache is
# what keeps the allowance from being spent by a handful of people.
# DEMO_KEY works without signing up and allows 30 requests an hour, which
# is enough to develop against and not enough to ship on.
USDA_FDC_API_KEY = os.getenv("USDA_FDC_API_KEY", "DEMO_KEY")

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@repbase.local')
